name: sphinx-build-deploy

on:
  push:
    branches:
    - master

  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout repo
      uses: actions/checkout@v2.3.4
    -
      name: Sphinx build - html
      run: docker run --rm -v $PWD:/docs bwibo/sphinx-rtd make html
    -
      name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages
        folder: src/_build/html
